import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  // const   = api.shoppingItem.getAll.useQuery();
  //const [shoppingItems, setShoppingItems] = useState<ShoppingItem[]>([]);
  const { data: shoppingItems } = api.shoppingItem.getAll.useQuery();
  const context = api.useContext();
  const { mutate } = api.shoppingItem.create.useMutation({
    onSuccess: async () => {
      await context.shoppingItem.invalidate();
    },
  });
  const handleClick = () => {
    // 1. create a new shopping item
    mutate({ name: "shopping item 1" });
    // 2. append to the shopping list
    // if (data) {
    //   setShoppingItems([...shoppingItems, data]);
    // }
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {JSON.stringify(shoppingItems)}
        <button onClick={handleClick}>Create Item</button>
      </main>
    </>
  );
}
